# Generated by Django 3.2.4 on 2021-06-10 22:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeavaliacao',
            unique_together={('user_id', 'avaliacao')},
        ),
    ]
