# Generated by Django 3.2.4 on 2021-06-08 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.IntegerField(default=2021, verbose_name='Ano de Lançamento')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('qtd_temporadas', models.PositiveSmallIntegerField(verbose_name='Número de temporadas')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('elenco', models.TextField(verbose_name='Elenco')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.categoria', verbose_name='Categoria')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.IntegerField(default=2021, verbose_name='Ano de Lançamento')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Volume')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.categoria', verbose_name='Categoria')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.IntegerField(default=2021, verbose_name='Ano de Lançamento')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('volume', models.PositiveSmallIntegerField(null=True, verbose_name='Volume')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('elenco', models.TextField(verbose_name='Elenco')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.categoria', verbose_name='Categoria')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
